package com.publicstaticfinalgames.drugs.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

//Date: 9/1/2014 4:54:09 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

public class ModelDryingRack extends ModelBase
{
	// fields
	public ModelRenderer Shape5;
	public ModelRenderer Shape6;
	public ModelRenderer Shape7;
	public ModelRenderer Shape8;
	public ModelRenderer Shape9;
	public ModelRenderer Shape10;
	public ModelRenderer Shape11;
	public ModelRenderer Shape12;
	public ModelRenderer Shape1;
	public ModelRenderer Shape2;
	public ModelRenderer Shape3;
	public ModelRenderer Shape4;

	public ModelDryingRack()
	{
		textureWidth = 64;
		textureHeight = 32;

		Shape5 = new ModelRenderer(this, 0, 0);
		Shape5.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape5.setRotationPoint(-8F, 8F, 7F);
		Shape5.setTextureSize(64, 32);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 0, 0);
		Shape6.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape6.setRotationPoint(-8F, 8F, 4F);
		Shape6.setTextureSize(64, 32);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 0, 0);
		Shape7.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape7.setRotationPoint(-8F, 8F, 1F);
		Shape7.setTextureSize(64, 32);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 0, 0);
		Shape8.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape8.setRotationPoint(-8F, 8F, -2F);
		Shape8.setTextureSize(64, 32);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 0, 0);
		Shape9.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape9.setRotationPoint(-8F, 8F, -5F);
		Shape9.setTextureSize(64, 32);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 0, 0);
		Shape10.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape10.setRotationPoint(-8F, 8F, -8F);
		Shape10.setTextureSize(64, 32);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 0, 0);
		Shape11.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape11.setRotationPoint(7F, 8F, 8F);
		Shape11.setTextureSize(64, 32);
		Shape11.mirror = true;
		setRotation(Shape11, 0F, 1.570796F, 0F);
		Shape12 = new ModelRenderer(this, 0, 0);
		Shape12.addBox(0F, 0F, 0F, 16, 1, 1);
		Shape12.setRotationPoint(-8.2F, 8F, 8F);
		Shape12.setTextureSize(64, 32);
		Shape12.mirror = true;
		setRotation(Shape12, 0F, 1.570796F, 0F);
		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 2, 1);
		Shape1.setRotationPoint(-6F, 8F, 7F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 1.570796F);
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(0F, 0F, 0F, 16, 2, 1);
		Shape2.setRotationPoint(8F, 8F, 7F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 1.570796F);
		Shape3 = new ModelRenderer(this, 0, 0);
		Shape3.addBox(0F, 0F, 0F, 16, 2, 1);
		Shape3.setRotationPoint(-6F, 8F, -8F);
		Shape3.setTextureSize(64, 32);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, 1.570796F);
		Shape4 = new ModelRenderer(this, 0, 0);
		Shape4.addBox(0F, 0F, 0F, 16, 2, 1);
		Shape4.setRotationPoint(8F, 8F, -8F);
		Shape4.setTextureSize(64, 32);
		Shape4.mirror = true;
		setRotation(Shape4, 0.0174533F, 0F, 1.570796F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		// setRotationAngles(f, f1, f2, f3, f4, f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}

// // Date: 2014-05-25 15:28:09
// // Template version 1.1
// // Java generated by Techne
// // Keep in mind that you still need to fill in some blanks
// // - ZeuX
//
// package com.publicstaticfinalgames.drugs.models;
//
// import net.minecraft.client.model.ModelBase;
// import net.minecraft.client.model.ModelRenderer;
// import net.minecraft.entity.Entity;
//
// public class ModelDryingRack extends ModelBase {
// //fields
// public ModelRenderer Shape1;
// public ModelRenderer Shape2;
// public ModelRenderer Shape3;
// public ModelRenderer Shape4;
// public ModelRenderer Shape5;
// public ModelRenderer Shape6;
// public ModelRenderer Shape7;
// public ModelRenderer Shape8;
// public ModelRenderer Shape9;
// public ModelRenderer Shape10;
// public ModelRenderer Shape11;
// public ModelRenderer Shape12;
//
// public ModelDryingRack() {
// textureWidth = 64;
// textureHeight = 32;
//
// Shape1 = new ModelRenderer(this, 0, 0);
// Shape1.addBox(0F, 0F, 0F, 12, 1, 1);
// Shape1.setRotationPoint(-0.5F, 14F, 0F);
// Shape1.setTextureSize(64, 32);
// Shape1.mirror = true;
// setRotation(Shape1, 0F, -0.9948377F, 0.9250245F);
// Shape2 = new ModelRenderer(this, 0, 0);
// Shape2.addBox(0F, 0F, 0F, 12, 1, 1);
// Shape2.setRotationPoint(-0.5F, 14F, 0F);
// Shape2.setTextureSize(64, 32);
// Shape2.mirror = true;
// setRotation(Shape2, 0F, 1.029744F, 0.9075712F);
// Shape3 = new ModelRenderer(this, 0, 0);
// Shape3.addBox(0F, 0F, 0F, 12, 1, 1);
// Shape3.setRotationPoint(-0.5F, 14F, 0F);
// Shape3.setTextureSize(64, 32);
// Shape3.mirror = true;
// setRotation(Shape3, 0F, -3.141593F, -0.5250245F);
// Shape4 = new ModelRenderer(this, 0, 0);
// Shape4.addBox(0F, 0F, 0F, 3, 1, 3);
// Shape4.setRotationPoint(-1.7F, 14F, -1.5F);
// Shape4.setTextureSize(64, 32);
// Shape4.mirror = true;
// setRotation(Shape4, 0F, 0F, 0F);
// Shape5 = new ModelRenderer(this, 0, 0);
// Shape5.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape5.setRotationPoint(-8F, 13F, 7F);
// Shape5.setTextureSize(64, 32);
// Shape5.mirror = true;
// setRotation(Shape5, 0F, 0F, 0F);
// Shape6 = new ModelRenderer(this, 0, 0);
// Shape6.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape6.setRotationPoint(-8F, 13F, 4F);
// Shape6.setTextureSize(64, 32);
// Shape6.mirror = true;
// setRotation(Shape6, 0F, 0F, 0F);
// Shape7 = new ModelRenderer(this, 0, 0);
// Shape7.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape7.setRotationPoint(-8F, 13F, 1F);
// Shape7.setTextureSize(64, 32);
// Shape7.mirror = true;
// setRotation(Shape7, 0F, 0F, 0F);
// Shape8 = new ModelRenderer(this, 0, 0);
// Shape8.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape8.setRotationPoint(-8F, 13F, -2F);
// Shape8.setTextureSize(64, 32);
// Shape8.mirror = true;
// setRotation(Shape8, 0F, 0F, 0F);
// Shape9 = new ModelRenderer(this, 0, 0);
// Shape9.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape9.setRotationPoint(-8F, 13F, -5F);
// Shape9.setTextureSize(64, 32);
// Shape9.mirror = true;
// setRotation(Shape9, 0F, 0F, 0F);
// Shape10 = new ModelRenderer(this, 0, 0);
// Shape10.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape10.setRotationPoint(-8F, 13F, -8F);
// Shape10.setTextureSize(64, 32);
// Shape10.mirror = true;
// setRotation(Shape10, 0F, 0F, 0F);
// Shape11 = new ModelRenderer(this, 0, 0);
// Shape11.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape11.setRotationPoint(7F, 13F, 8F);
// Shape11.setTextureSize(64, 32);
// Shape11.mirror = true;
// setRotation(Shape11, 0F, 1.570796F, 0F);
// Shape12 = new ModelRenderer(this, 0, 0);
// Shape12.addBox(0F, 0F, 0F, 16, 1, 1);
// Shape12.setRotationPoint(-8F, 13F, 8F);
// Shape12.setTextureSize(64, 32);
// Shape12.mirror = true;
// setRotation(Shape12, 0F, 1.570796F, 0F);
// }
//
// public void render(Entity entity, float f, float f1, float f2, float f3,
// float f4, float f5) {
// super.render(entity, f, f1, f2, f3, f4, f5);
// Shape1.render(f5);
// Shape2.render(f5);
// Shape3.render(f5);
// Shape4.render(f5);
// Shape5.render(f5);
// Shape6.render(f5);
// Shape7.render(f5);
// Shape8.render(f5);
// Shape9.render(f5);
// Shape10.render(f5);
// Shape11.render(f5);
// Shape12.render(f5);
// }
//
// private void setRotation(ModelRenderer model, float x, float y, float z) {
// model.rotateAngleX = x;
// model.rotateAngleY = y;
// model.rotateAngleZ = z;
// }
// }
